
update_user_settings:
  description: Update a user setting 

  fields:
    device:
      description: Name of setting to change
      example: 'device1'

    obj:
      description: An object containing the value
      example: 'obj.value'